In [ ]:
from selenium import webdriver
import sys
import pandas as pd
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
import warnings 
warnings.filterwarnings('ignore')

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get('https://www.linkedin.com/')
input("Press enter after login")

In [4]:
def follow_activities():
        
    # https://docs.google.com/spreadsheets/d/1qvQ3Fc35EEcq0AIrw8tvF62L5xBmHcPiKCmDZ-nqVgk/edit?usp=sharing
    sheet_id = "1qvQ3Fc35EEcq0AIrw8tvF62L5xBmHcPiKCmDZ-nqVgk" #update ID here
    df_sheet_base= "https://docs.google.com/spreadsheets/d/{0}/gviz/tq?tqx=out:csv&sheet=".format(sheet_id)
    sheet_name = "Sheet1"
    df = pd.read_csv(df_sheet_base + sheet_name)
    # df

    for i in range(len(df)):
        try:    
            link = df["LinkedIn Profile URL"][i]
            driver.get(link)
            # to follow Activity
            follow_button = driver.find_element("xpath",'//div[@class="p2"]')
            sleep(2)
            follow_button.click()
            sleep(2)
        except:
            print(sys.exc_info()[0])

     S.No              Name                               LinkedIn Profile URL
0       1     Sabeen Shahid  https://www.linkedin.com/in/sabeen-shahid-9433...
1       2        Risfa John             https://www.linkedin.com/in/risfajohn/
2       3       Asma Shakil  https://www.linkedin.com/in/asma-shakil-805b41...
3       4    Fatima Tanveer     https://www.linkedin.com/in/fatima-tanveer-04/
4       5    Mahnoor Masood        https://www.linkedin.com/in/mahnoor-masood/
..    ...               ...                                                ...
142   144    Anum Shahjahan       https://www.linkedin.com/in/anum-s-66b44294/
143   145         Manan Gul    https://www.linkedin.com/in/manan-gul-973b2386/
144   146         Saud Anis    https://www.linkedin.com/in/saud-anis-2b2ba266/
145   147   Munazza Kasmani  https://www.linkedin.com/in/munazza-kasmani-59...
146   148  Syed Urooj Ahmed  https://www.linkedin.com/in/syeda-urooj-ahmed-...

[147 rows x 3 columns]